apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: iskprinter-master
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- if ne .Values.host "localhost" }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: "tls-{{ .Values.host }}"
  {{- end}}
  rules:
  - host: {{ .Values.host }}
